# Author: Kang Lin<kl222@126.com>

name: build

env:
  artifact_path: artifact_path
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Calendar_VERSION: 1.0.22

on: 
  push:
  pull_request:

jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml

  appimage:
    uses: ./.github/workflows/appimage.yml
    secrets: inherit

  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  msvc:
    uses: ./.github/workflows/msvc.yml

  mingw:
    uses: ./.github/workflows/mingw.yml

  macos:
    uses: ./.github/workflows/macos.yml

  android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

  deploy:
    #if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [ubuntu, appimage, msvc, macos, android, docker]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: clean test tag
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
        continue-on-error: true
        run: |
          gh release delete test_${{ github.ref_name }} -y --cleanup-tag

      - name: Download ubuntu
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ needs.ubuntu.outputs.name }}*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download appimage
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ needs.appimage.outputs.name }}*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download docker
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ needs.docker.outputs.name }}*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download msvc
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ needs.msvc.outputs.name }}*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download macos
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ needs.macos.outputs.name }}*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Download android
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ needs.android.outputs.name }}*
          path: ${{ env.artifact_path }}
          merge-multiple: true

      - name: Process configure file
        run: |
          git clone https://github.com/KangLin/RabbitCommon.git
          ./RabbitCommon/Install/MergeJsonFile.sh \
              "${{ github.workspace }}/update.json" \
              "${{ env.artifact_path }}" "${{ env.artifact_path }}/version.json"
          rm ${{ env.artifact_path }}/*.json

      - name: Add change log file in Release.md file
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          if [ -f ${{github.workspace}}/Script/common.sh ]; then
              source ${{github.workspace}}/Script/common.sh
              content=$(<"${{github.workspace}}/ChangeLog.md")
              if [[ $content =~ "${{env.Calendar_VERSION}}" ]]; then
                echo "## :us: Change log" >> ${{github.workspace}}/Release.md
                echo "" >> ${{github.workspace}}/Release.md
                get_section ${{github.workspace}}/ChangeLog.md >> ${{github.workspace}}/Release.md
                echo "" >> ${{github.workspace}}/Release.md
              fi
              # content=$(<"${{github.workspace}}/ChangeLog_zh_CN.md")
              # if [[ $content =~ "${{env.Calendar_VERSION}}" ]]; then
              #   echo "## :cn: 修改日志" >> ${{github.workspace}}/Release.md
              #   echo "" >> ${{github.workspace}}/Release.md
              #   get_section ${{github.workspace}}/ChangeLog_zh_CN.md >> ${{github.workspace}}/Release.md
              #   echo "" >> ${{github.workspace}}/Release.md
              # fi
          fi
          echo "-------------------------" >> ${{github.workspace}}/Release.md
          # 因为其它网站也可能需要，所以用完整的 URL
          echo "|:us: English|:cn: 中文|" >> ${{github.workspace}}/Release.md
          echo "| :-    |:- |" >> ${{github.workspace}}/Release.md
          echo "|[Change log](https://github.com/KangLin/Calendar/blob/v${{env.Calendar_VERSION}}/ChangeLog.md)|[修改日志](https://github.com/KangLin/Calendar/blob/v${{env.Calendar_VERSION}}/ChangeLog_zh_CN.md)|" >> ${{github.workspace}}/Release.md
          echo "|Full Change: [${{env.Calendar_VERSION_PRE}}...v${{env.Calendar_VERSION}}](https://github.com/KangLin/Calendar/compare/${{env.Calendar_VERSION_PRE}}...v${{env.Calendar_VERSION}})|全部修改: [${{env.Calendar_VERSION_PRE}}...v${{env.Calendar_VERSION}}](https://github.com/KangLin/Calendar/compare/${{env.Calendar_VERSION_PRE}}...v${{env.Calendar_VERSION}})|" >> ${{github.workspace}}/Release.md
          BUILD_TIME=`date --rfc-3339=second`
          echo "|Build time: $BUILD_TIME|构建时间：$BUILD_TIME|" >> ${{github.workspace}}/Release.md
          echo "|Supported platforms: [Qt5](https://doc.qt.io/qt-5/supported-platforms.html) [Qt6](https://doc.qt.io/qt-6/supported-platforms.html)|支持平台: [Qt5](https://doc.qt.io/qt-5/supported-platforms.html) [Qt6](https://doc.qt.io/qt-6/supported-platforms.html)|" >> ${{github.workspace}}/Release.md
          echo "|[File checksum](https://github.com/KangLin/Calendar/releases/download/${{ github.ref_name }}/CheckSum.md)|[文件检验和](https://github.com/KangLin/Calendar/releases/download/${{ github.ref_name }}/CheckSum.md)|" >> ${{github.workspace}}/Release.md
          echo "|[Online development document](https://Calendar.sourceforge.io/${{ github.ref_name }}/English/html/index.html)|[在线开发文档](https://Calendar.sourceforge.io/${{ github.ref_name }}/Chinese/html/index.html)|" >> ${{github.workspace}}/Release.md
          echo "" >> ${{github.workspace}}/Release.md

      - name: Add test comment in Release.md file
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "**This release is for development and testing purposes only!**" >> ${{github.workspace}}/Release.md
          if [ -f ${{github.workspace}}/Script/common.sh ]; then
              source ${{github.workspace}}/Script/common.sh
              content=$(<"${{github.workspace}}/ChangeLog.md")
              if [[ $content =~ "${{env.Calendar_VERSION}}" ]]; then
                echo "## :us: Change log" >> ${{github.workspace}}/Release.md
                echo "" >> ${{github.workspace}}/Release.md
                get_section ${{github.workspace}}/ChangeLog.md >> ${{github.workspace}}/Release.md
                echo "-------------------------" >> ${{github.workspace}}/Release.md
              fi
          fi
          echo "" >> ${{github.workspace}}/Release.md
          echo "Commit: [${{github.sha}}](https://github.com/KangLin/Calendar/commit/${{github.sha}})" >> ${{github.workspace}}/Release.md
          echo "" >> ${{github.workspace}}/Release.md
          echo "Build time: `date --rfc-3339=second`" >> ${{github.workspace}}/Release.md
          echo "" >> ${{github.workspace}}/Release.md
          echo "[:us: Change log](https://github.com/KangLin/Calendar/blob/test_${{ github.ref_name }}/ChangeLog.md)" >> ${{github.workspace}}/Release.md
          echo "" >> ${{github.workspace}}/Release.md
          echo "[File checksum](https://github.com/KangLin/Calendar/releases/download/test_${{ github.ref_name }}/CheckSum.md)" >> ${{github.workspace}}/Release.md
          echo "" >> ${{github.workspace}}/Release.md

      - name: Add download
        run: |
          export BRANCH_NAME="${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "master" ]; then
              export BRANCH_NAME="test_${{ github.ref_name }}"
          fi
          echo "## Download:" >> ${{github.workspace}}/Release.md
          echo "" >> ${{github.workspace}}/Release.md
          echo "|       | x86-64 (64-bit) | x86-32 (32-bit) | AArch64 (ARM64) | ARMv7 (32-bit) |:us: Comment|:cn: 备注|" >> ${{github.workspace}}/Release.md
          echo "|:-     | :-------------- | :-------------- | :-------------- | :------------- |:-----------|:--------|" >> ${{github.workspace}}/Release.md
          echo "|Windows|[EXE](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/Calendar_v${{env.Calendar_VERSION}}_win64_msvc2022_64_qt6.10.3.exe)|[EXE](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/Calendar_v${{env.Calendar_VERSION}}_win32_msvc2017_qt5.12.12.exe)|[EXE](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/Calendar_v${{env.Calendar_VERSION}}_win64_msvc2022_arm64_qt6.10.3.exe)| |Supported platforms:<br> [x86-32(Qt5)](https://doc.qt.io/qt-5/supported-platforms.html)<br> [x86-64(Qt6)](https://doc.qt.io/qt-6/supported-platforms.html)|支持平台：<br> [x86-32(Qt5)](https://doc.qt.io/qt-5/supported-platforms.html)<br> [x86-64(Qt6)](https://doc.qt.ac.cn/qt-6/supported-platforms.html)|" >> ${{github.workspace}}/Release.md
          echo "|Android|[APK](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/Calendar_v${{env.Calendar_VERSION}}_android_x86_64_qt6.10.3_Release.apk)| |[APK](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/Calendar_v${{env.Calendar_VERSION}}_android_arm64_v8a_qt6.10.3_Release.apk)| | | |" >> ${{github.workspace}}/Release.md
          echo "|Linux|[zip file of install AppImage](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/Calendar_${{env.Calendar_VERSION}}_Linux_x86_64_Setup.zip)| |[zip file of install AppImage](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/Calendar_${{env.Calendar_VERSION}}_Linux_aarch64_Setup.zip)| | | |" >> ${{github.workspace}}/Release.md
          echo "|Ubuntu 26.04 (resolute)|[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_ubuntu26.04_x86_64.deb)| |[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_ubuntu26.04_aarch64.deb)| | Run \`sudo apt install ./rabbitcalendar_*.deb\` to install it. | 运行命令 \`sudo apt install ./rabbitcalendar_*.deb\` 进行安装。 |" >> ${{github.workspace}}/Release.md
          echo "|Ubuntu 24.04 (noble)|[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_ubuntu24.04_x86_64.deb)| |[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_ubuntu24.04_aarch64.deb)| | Run \`sudo apt install ./rabbitcalendar_*.deb\` to install it.|运行命令 \`sudo apt install ./rabbitcalendar_*.deb\` 进行安装。 |" >> ${{github.workspace}}/Release.md
          echo "|Debian 13 (trixie)|[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_debian13_x86_64.deb)| |[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_debian13_aarch64.deb)| | | |" >> ${{github.workspace}}/Release.md
          echo "|Debian 12 (Bookworm)|[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_debian12_x86_64.deb)| |[DEB](https://github.com/KangLin/Calendar/releases/download/${BRANCH_NAME}/rabbitcalendar_${{env.Calendar_VERSION}}_debian12_aarch64.deb)| | | |" >> ${{github.workspace}}/Release.md

      - name: Make note file
        run: |
          echo "" >> ${{github.workspace}}/Release.md
          echo "File checksum:" >> ${{github.workspace}}/CheckSum.md
          echo "|File|Checksum(md5)|" >> ${{github.workspace}}/CheckSum.md
          echo "| :- |    :-       |" >> ${{github.workspace}}/CheckSum.md
          cd ${{ env.artifact_path }}
          for file in *
          do
            echo "$file"
            if [ -f $file ]; then
                if [ "${file##*.}" != "xml" ] && [ "${file##*.}" != "json" ]; then
                    SumMd5=`md5sum $file | awk '{print  "|", $2, "|", $1, "|"}'`
                    Sum256=`sha256sum $file | awk '{print $1, "|"}'`
                    echo "${SumMd5}${Sum256}" >> ${{github.workspace}}/CheckSum.md
                fi
            else
               rm -fr $file
            fi
          done

      - name: Upload To Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        continue-on-error: true
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-file ${{github.workspace}}/Release.md

      - name: Upload To Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        #continue-on-error: true
        run: |
          gh release upload ${{ github.ref_name }} ${{github.workspace}}/${{ env.artifact_path }}/* ${{github.workspace}}/Release.md ${{github.workspace}}/update.json

      - name: Upload test tag To Github Release
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
        run: |
          gh release create test_${{ github.ref_name }} --prerelease --latest=false --title "Recently developed build - test_${{ github.ref_name }}" --notes-file ${{github.workspace}}/Release.md
          gh release upload test_${{ github.ref_name }} --clobber ${{github.workspace}}/${{ env.artifact_path }}/* ${{github.workspace}}/Release.md ${{github.workspace}}/CheckSum.md
