name: ubuntu

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    strategy:
      matrix:
        os: [Ubuntu-20.04, Ubuntu-18.04]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        BUILD_TYPE: [Release, Debug]

    runs-on: ${{matrix.os}}
    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOSL_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_ubuntu_2022_02_14
      Calendar_VERSION: 1.0.3

    steps:
    - name: core dump infomations
      if: false
      run: |
        echo "# ulimit -a"
        ulimit -a
        echo "# cat /proc/sys/kernel/core_pattern"
        cat /proc/sys/kernel/core_pattern
        echo "# ulimit -c unlimited"
        ulimit -c unlimited
        echo "# sudo sysctl -w kernel.core_pattern=core"
        sudo sysctl -w kernel.core_pattern=${{github.workspace}}/core
        echo "# ulimit -a"
        ulimit -a
        echo "# cat /proc/sys/kernel/core_pattern"
        cat /proc/sys/kernel/core_pattern

#        See: https://www.cnblogs.com/cong-wang/p/15026524.html
#        Naming of core dump files
#               By default, a core dump file is named core, but the /proc/sys/kernel/core_pattern file (since  Linux  2.6  and
#               2.4.21)  can  be  set  to  define a template that is used to name core dump files.  The template can contain %
#               specifiers which are substituted by the following values when a core file is created:
#
#                   %%  a single % character
#                   %c  core file size soft resource limit of crashing process (since Linux 2.6.24)
#                   %d  dump mode—same as value returned by prctl(2) PR_GET_DUMPABLE (since Linux 3.7)
#                   %e  executable filename (without path prefix)
#                   %E  pathname of executable, with slashes ('/') replaced by exclamation marks ('!') (since Linux 3.0).
#                   %g  (numeric) real GID of dumped process
#                   %h  hostname (same as nodename returned by uname(2))
#                   %i  TID of thread that triggered core dump, as seen in the PID  namespace  in  which  the  thread  resides
#                       (since Linux 3.18)
#                   %I  TID of thread that triggered core dump, as seen in the initial PID namespace (since Linux 3.18)
#                   %p  PID of dumped process, as seen in the PID namespace in which the process resides
#                   %P  PID of dumped process, as seen in the initial PID namespace (since Linux 3.12)
#                   %s  number of signal causing dump
#                   %t  time of dump, expressed as seconds since the Epoch, 1970-01-01 00:00:00 +0000 (UTC)
#                   %u  (numeric) real UID of dumped process

    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0

    - uses: snickerbockers/submodules-init@v4

    - name: make_directory
      run: |
        cmake -E make_directory ${{env.SOURCE_DIR}}
        cmake -E make_directory ${{env.TOOSL_DIR}}
        cmake -E make_directory ${{env.INSTALL_DIR}}

    - name: git clone RabbitCommon
      working-directory: ${{env.SOURCE_DIR}}
      run: git clone https://github.com/KangLin/RabbitCommon.git

#    - name: apt helper action
#      uses: ryankurte/action-apt@v0.3.0
#      with:
#        arch: amd64
#        packages: xvfb xpra libglu1-mesa-dev libpulse-mainloop-glib0 cmake build-essential debhelper dh-systemd fakeroot graphviz qttools5-dev qttools5-dev-tools qtbase5-dev qtbase5-dev-tools qtmultimedia5-dev qtlocation5-dev libqt5svg5-dev libutf8proc-dev libqtermwidget5-0-dev libpam0g-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libx11-xcb-dev libx11-dev libxfixes-dev qtwebengine5-dev gdb

    - name: apt helper action
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install xvfb xpra \
            libglu1-mesa-dev libpulse-mainloop-glib0 \
            cmake build-essential \
            debhelper fakeroot graphviz \
            qttools5-dev qttools5-dev-tools qtbase5-dev qtbase5-dev-tools \
            qtmultimedia5-dev qtlocation5-dev libqt5svg5-dev \
            qtwebengine5-dev libqtermwidget5-0-dev \
            libutf8proc-dev libpam0g-dev \
            libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libx11-xcb-dev \
            libx11-dev libxfixes-dev \
            libsqlite3-dev \
            libodbc1 

    - name: Cache installed
      uses: actions/cache@v2
      id: cache-installed
      with:
        path: |
          ${{env.INSTALL_DIR}}
        key: cache-installed-ubuntu-${{matrix.os}}-${{matrix.BUILD_TYPE}}_2022_12_26

    - name: build log4qt
      working-directory: ${{env.SOURCE_DIR}}
      env:
        QT_ROOT: /usr/lib/`uname -m`-linux-gnu/qt5
      run: |
        if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/Log4Qt ]; then
            git clone https://github.com/KangLin/Log4Qt.git
            cd Log4Qt
            cmake -E make_directory build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
                -DQT_DIR=${{env.QT_ROOT}}/lib/cmake/Qt5 \
                -DQt5_DIR=${{env.QT_ROOT}}/lib/cmake/Qt5 \
                -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_DIR}} \
                -DCMAKE_PREFIX_PATH=${{env.QT_ROOT}} \
                -DLOG4QT_ENABLE_EXAMPLES=OFF \
                -DLOG4QT_ENABLE_TESTS=OFF
            cmake --build . --config ${{matrix.BUILD_TYPE}}
            cmake --build . --config ${{matrix.BUILD_TYPE}} --target install/strip
        fi

    - name: build_debpackage.sh
      working-directory: ${{github.workspace}}
      env:
        RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        Log4Qt_DIR: ${{env.INSTALL_DIR}}/lib/cmake/Log4Qt
      run: |
        ./build_debpackage.sh /usr/lib/`uname -m`-linux-gnu/qt5
        cp ../calendar_${{env.Calendar_VERSION}}_amd64.deb calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb
        md5sum calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb > calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb.md5sum

    - name: update xml file
      if: ${{ matrix.BUILD_TYPE == 'Release' && matrix.os == 'Ubuntu-20.04'}}
      working-directory: ${{github.workspace}}
      #continue-on-error: true
      run: |
        #sudo apt update -y -qq
        #sudo apt-get install -y -qq xvfb xpra
        sudo Xvfb :999 -ac &
        export DISPLAY=:999.0
        echo "Install rabbit remote control ......"
        sudo apt install ./calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb
        echo "Update update_linux.xml ......"
        export QT_XCB_GL_INTEGRATION=none
        MD5SUM=`cat calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb.md5sum|awk '{print $1}'`
        echo "MD5SUM calendar_${{env.Calendar_VERSION}}_amd64_${{ matrix.os }}.deb: ${MD5SUM}"
        #ulimit -c unlimited
        #echo "# sudo sysctl -w kernel.core_pattern=core"
        #sudo sysctl -w kernel.core_pattern=${{github.workspace}}/core
        /opt/Calendar/bin/CalendarApp \
            -f "`pwd`/update_linux.xml" \
            -u "https://github.com/KangLin/Calendar/releases/download/v${{env.Calendar_VERSION}}/calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb;https://sourceforge.net/projects/Calendar/files/v${{env.Calendar_VERSION}}/calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb" \
            --md5 "${MD5SUM}" \
            --pf calendar_${{env.Calendar_VERSION}}_amd64_${{ matrix.os }}.deb \
            -m "v${{env.Calendar_VERSION}}"

    - name: update
      if: ${{ matrix.BUILD_TYPE == 'Release' }}
      uses: actions/upload-artifact@v2
      with:
          name: Calendar_${{matrix.os}}
          path: |
            calendar_*.deb
            update_linux.xml

    - name: Upload To Github Release
      if: ${{ matrix.BUILD_TYPE == 'Release' && startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        prerelease: false
        body: |
           [:cn: 修改日志](ChangeLog.md)
        files: |
            ${{github.workspace}}/update_linux.xml
            ${{github.workspace}}/calendar_*.deb
            ${{github.workspace}}/calendar_${{env.Calendar_VERSION}}_amd64_${{matrix.os}}.deb.md5sum
